import type { Metadata } from 'next'
import { Unbounded } from 'next/font/google'
import './globals.css'

const unbonded = Unbounded({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={unbonded.className}>
        <main className=''>
          {children}
        </main>
      </body>
    </html>
  )
}
